AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: "Deploys the environment stack for the Pressing managment Site application."
Parameters:
  EnvId:
    Type: String
    Description: Environment Id (used to namespace resources)
    AllowedPattern: "[a-z][a-z0-9]{2,19}"
    ConstraintDescription: Must be lower case letters between 3 and 20 characters.
  ProjectId:
    Type: String
    Description: Project Id (used to determine the specific project)
    AllowedPattern: "^[a-z][a-z0-9-]{2,49}$"
    ConstraintDescription: Must be lower case letters, digits, or hyphens (3-50 characters).
  InfraArtifactsBucket:
    Type: String
    Description: The bucket where the infra artifacts are stored (specifically the cloudformation templates).
  InfraReleaseHash:
    Type: String
    Description: The id of the cloudformation templates to use for nested stacks. In CD this will be set to the git sha for the current commi
  ClientImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the client service.
  ServerImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the server service.
  ReleaseTarget:
    Type: String
    Description: |
      The git branch (or tag) that is being be deployed to this environment.
      This is used for tagging resources in the environment for information and debugging purposes.
  DomainName:
    Type: String
    Description: The domain name for the environment.

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${ProjectId}-${EnvId}"

  # VpcStack set up VPC with 2 AZs.
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
        IsDevelopmentGrade: true
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
        - Key: ReleaseTarget
          Value: !Ref "ReleaseTarget"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/vpc.yaml",
          ],
        ]

  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
        VpcId: !GetAtt VpcStack.Outputs.VPC
        PrivateSubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        NumPrivateNodes: 1
        InstanceType: t3.micro
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
        - Key: ReleaseTarget
          Value: !Ref "ReleaseTarget"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/ecs.yaml",
          ],
        ]

  # WebCert deploys the web certificates.
  WebCert:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref "DomainName"
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
        - !Sub "api.${DomainName}"
      ValidationMethod: DNS
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"

  # LoadBalancerStack deploys the default load balancer.
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VpcStack, WebCert]
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
        VPC: !GetAtt VpcStack.Outputs.VPC
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPublic,
              !GetAtt VpcStack.Outputs.SubnetBPublic,
            ],
          ]
        CertificateArn: !Ref WebCert
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/load_balancer.yaml",
          ],
        ]

  EcsSecurityGroupALBports:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !GetAtt EcsStack.Outputs.EcsSecurityGroupId
      IpProtocol: tcp
      FromPort: 80
      ToPort: 61000
      SourceSecurityGroupId: !GetAtt LoadBalancerStack.Outputs.LoadBalancerSecurityGroupId

  ThirdPartySecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/components/third_party_secrets.yaml",
          ],
        ]


  ClientStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        DomainName: !Ref DomainName
        LoadBalancerCanonicalHostedZoneID: !GetAtt LoadBalancerStack.Outputs.LoadBalancerCanonicalHostedZoneID
        LoadBalancerDNSName: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
        HttpsListener: !GetAtt LoadBalancerStack.Outputs.HttpsListener
        Image: !Ref ClientImageTag
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/client.yaml",
          ],
        ]

  SeverStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      Parameters:
        EnvId: !Sub "${ProjectId}-${EnvId}"
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        DomainName: !Ref DomainName
        LoadBalancerCanonicalHostedZoneID: !GetAtt LoadBalancerStack.Outputs.LoadBalancerCanonicalHostedZoneID
        LoadBalancerDNSName: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
        HttpsListener: !GetAtt LoadBalancerStack.Outputs.HttpsListener
        MongoDBSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.MongoDBSecretArn"
        CloudinarySecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.CloudinarySecretArn"
        JWTSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.JWTSecretArn"
        AdminSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.AdminSecretArn"
        SmtpSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.SmtpSecretArn"
        TwilioSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.TwilioSecretArn"
        DirectoryAdminSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.DirectoryAdminSecretArn"
        ExchangeRateSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.ExchangeRateSecretArn"
        AccountpeSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.AccountpeSecretArn"
        Image: !Ref ServerImageTag
      Tags:
        - Key: EnvId
          Value: !Sub "${ProjectId}-${EnvId}"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/server.yaml",
          ],
        ]
  