AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the Node.js server as a Lambda function behind API Gateway"

Parameters:
  EnvId:
    Type: String
    Description: Environment Id for namespacing resources.

  DomainName:
    Type: String
    Description: Base domain (e.g., example.com).

  InfraArtifactsBucket:
    Type: String
    Description: The S3 bucket where the built server artifact zip is stored.

  ServerArtifactS3Key:
    Type: String
    Description: The S3 key (path) for the zipped server artifact.

  WebCertArn:
    Type: String
    Description: The ARN of the ACM certificate for HTTPS.

  MongoDBSecretArn:
    Type: String
  CloudinarySecretArn:
    Type: String
  JWTSecretArn:
    Type: String
  AdminSecretArn:
    Type: String
  SmtpSecretArn:
    Type: String
  TwilioSecretArn:
    Type: String
  DirectoryAdminSecretArn:
    Type: String
  ExchangeRateSecretArn:
    Type: String
  AccountpeSecretArn:
    Type: String

Resources:
  # --- Lambda Execution Role ---
  ServerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvId}-server-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AllowSecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource:
                  - !Ref MongoDBSecretArn
                  - !Ref CloudinarySecretArn
                  - !Ref JWTSecretArn
                  - !Ref AdminSecretArn
                  - !Ref SmtpSecretArn
                  - !Ref TwilioSecretArn
                  - !Ref DirectoryAdminSecretArn
                  - !Ref ExchangeRateSecretArn
                  - !Ref AccountpeSecretArn

  # --- Lambda Function ---
  ServerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${EnvId}-server-lambda"
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt ServerLambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: production
          MONGODB_SECRET_ARN: !Ref MongoDBSecretArn
          CLOUDINARY_SECRET_ARN: !Ref CloudinarySecretArn
          JWT_SECRET_ARN: !Ref JWTSecretArn
          ADMIN_SECRET_ARN: !Ref AdminSecretArn
          SMTP_SECRET_ARN: !Ref SmtpSecretArn
          TWILIO_SECRET_ARN: !Ref TwilioSecretArn
          DIRECTORY_ADMIN_SECRET_ARN: !Ref DirectoryAdminSecretArn
          EXCHANGE_RATE_SECRET_ARN: !Ref ExchangeRateSecretArn
          ACCOUNTPAY_SECRET_ARN: !Ref AccountpeSecretArn
      Code:
        S3Bucket: !Ref InfraArtifactsBucket
        S3Key: !Ref ServerArtifactS3Key

  # --- API Gateway ---
  ServerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${EnvId}-server-api"
      Description: "API Gateway for ${EnvId} Node.js Lambda backend"

  # Root resource ("/{proxy+}")
  RootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ServerApi.RootResourceId
      PathPart: "{proxy+}"
      RestApiId: !Ref ServerApi

  # Method - ANY
  ServerApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ServerApi
      ResourceId: !Ref RootResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - { LambdaArn: !GetAtt ServerLambda.Arn }

  # --- Deployment ---
  ServerApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ServerApiMethod
    Properties:
      RestApiId: !Ref ServerApi

  # --- Explicit Stage ---
  ServerApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      DeploymentId: !Ref ServerApiDeployment
      RestApiId: !Ref ServerApi
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          LoggingLevel: INFO
          DataTraceEnabled: true

  # Permission for API Gateway to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ServerLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerApi}/*"

  # --- Custom Domain for API ---
  ApiGatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub "api.${DomainName}"
      RegionalCertificateArn: !Ref WebCertArn
      EndpointConfiguration:
        Types: ["REGIONAL"]

  # Base path mapping for custom domain
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ServerApiStage
    Properties:
      DomainName: !Ref ApiGatewayDomain
      RestApiId: !Ref ServerApi
      Stage: !Ref ServerApiStage

  # --- Route53 Record for API ---
  ApiDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "api.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiGatewayDomain.RegionalHostedZoneId

Outputs:
  ApiUrl:
    Description: The custom domain URL for the API
    Value: !Sub "https://api.${DomainName}"

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref ServerLambda
