AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Node.js/Express API to ECS Fargate with ALB & Route53"

Parameters:
  EnvId:
    Type: String

  DomainName:
    Type: String

  InfraArtifactsBucket:
    Type: String

  ImageTag:
    Type: String

  WebCertArn:
    Type: String

  VpcId:
    Type: String

  PublicSubnetIds:
    Type: CommaDelimitedList

  PrivateSubnetIds:
    Type: CommaDelimitedList

  MongoDBSecretArn:
    Type: String
  CloudinarySecretArn:
    Type: String
  JWTSecretArn:
    Type: String
  AdminSecretArn:
    Type: String
  SmtpSecretArn:
    Type: String
  TwilioSecretArn:
    Type: String
  DirectoryAdminSecretArn:
    Type: String
  ExchangeRateSecretArn:
    Type: String
  AccountpeSecretArn:
    Type: String

# ------------------------------------------------------------
# IAM ROLES (Execution Role + Task Role)
# ------------------------------------------------------------

Resources:

  ServerTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvId}-server-exec-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ServerTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvId}-server-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowSecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref MongoDBSecretArn
                  - !Ref CloudinarySecretArn
                  - !Ref JWTSecretArn
                  - !Ref AdminSecretArn
                  - !Ref SmtpSecretArn
                  - !Ref TwilioSecretArn
                  - !Ref DirectoryAdminSecretArn
                  - !Ref ExchangeRateSecretArn
                  - !Ref AccountpeSecretArn

# ------------------------------------------------------------
# Networking
# ------------------------------------------------------------

  ServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Security group for ECS API (${EnvId})"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

# ------------------------------------------------------------
# ECS CLUSTER + TASK
# ------------------------------------------------------------

  ServerCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvId}-server-cluster"

  ServerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvId}-server-task"
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: ["FARGATE"]
      ExecutionRoleArn: !GetAtt ServerTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ServerTaskRole.Arn
      ContainerDefinitions:
        - Name: server
          Image: !Ref ImageTag
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
          Secrets:
            - Name: MONGODB_URI
              ValueFrom: !Ref MongoDBSecretArn
            - Name: CLOUDINARY_SECRET
              ValueFrom: !Ref CloudinarySecretArn
            - Name: JWT_SECRET
              ValueFrom: !Ref JWTSecretArn
            - Name: ADMIN_SECRET
              ValueFrom: !Ref AdminSecretArn
            - Name: SMTP_SECRET
              ValueFrom: !Ref SmtpSecretArn
            - Name: TWILIO_SECRET
              ValueFrom: !Ref TwilioSecretArn
            - Name: DIRECTORY_ADMIN_SECRET
              ValueFrom: !Ref DirectoryAdminSecretArn
            - Name: EXCHANGE_RATE_SECRET
              ValueFrom: !Ref ExchangeRateSecretArn
            - Name: ACCOUNTPAY_SECRET
              ValueFrom: !Ref AccountpeSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${EnvId}/server"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: server

# ------------------------------------------------------------
# ALB + Target Group + HTTPS Listener
# ------------------------------------------------------------

  ServerALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvId}-alb"
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ServerSG
      Subnets: !Ref PublicSubnetIds

  ServerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvId}-tg"
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  ServerALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ServerALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref WebCertArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ServerTargetGroup

# ------------------------------------------------------------
# ECS SERVICE
# ------------------------------------------------------------

  ServerECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ServerCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref ServerTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PrivateSubnetIds
          SecurityGroups:
            - !Ref ServerSG
      LoadBalancers:
        - TargetGroupArn: !Ref ServerTargetGroup
          ContainerName: server
          ContainerPort: 3000
      DependsOn: ServerALBListener

# ------------------------------------------------------------
# ROUTE53
# ------------------------------------------------------------

  ServerDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "api.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt ServerALB.DNSName
        HostedZoneId: !GetAtt ServerALB.CanonicalHostedZoneID

# ------------------------------------------------------------
# OUTPUTS
# ------------------------------------------------------------

Outputs:
  ServerApiUrl:
    Description: API URL
    Value: !Sub "https://api.${DomainName}"

  ServerECSServiceName:
    Description: ECS Service Name
    Value: !Ref ServerECSService
