AWSTemplateFormatVersion: 2010-09-09
Description: The Jsonproxy API service (FARGATE)

Parameters:
  EnvId:
    Type: String
    Description: Environment Id (used to namespace resources)
    AllowedPattern: "^[a-z][a-z0-9-]{2,49}$"
    ConstraintDescription: Must be lower case letters, digits, or hyphens (3-50 characters).

  VPC:
    Type: AWS::EC2::VPC::Id

  LogGroupName:
    Type: String
    Description: LogGroup name that should be use for the service

  ClusterArn:
    Type: String

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  Image:
    Type: String

  DesiredCount:
    Type: Number
    Default: 1

  DomainName:
    Type: String
    Description: The domain name for the environment where the service register a DNS record.

  LoadBalancerDNSName:
    Type: String
    Description: The DNS name of the load balancer that the service is registered with.

  LoadBalancerCanonicalHostedZoneID:
    Type: String
    Description: The canonical hosted zone ID of the load balancer.

  HttpsListener:
    Type: String
    Description: The ARN of the HTTPS listener to use.

  MongoDBSecretArn:
    Type: String

  CloudinarySecretArn:
    Type: String

  FapshiSecretArn:
    Type: String

  JWTSecretArn:
    Type: String

  AdminSecretArn:
    Type: String

  ContainerPort:
    Type: Number
    Default: 8000

  AppName:
    Type: String
    Default: "server"

Resources:

  # ------------------------------------------------------------
  # TASK DEFINITION
  # ------------------------------------------------------------
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvId}-${AppName}"
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: "512"
      Memory: "1024"
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref AppName
          Image: !Ref Image
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupName
              awslogs-stream-prefix: !Ref AppName
          Environment:
            - Name: PORT
              Value: !Ref ContainerPort
            - Name: FRONTEND_URL
              Value: !Sub "https://${DomainName}"
            - Name: BACKEND_URL
              Value: !Sub "https://api.${DomainName}"
          Secrets:
            - Name: MONGO_URI
              ValueFrom: !Sub "${MongoDBSecretArn}:mongo_uri::"
            - Name: CLOUDINARY_CLOUD_NAME
              ValueFrom: !Sub "${CloudinarySecretArn}:cloudinary_cloud_name::"
            - Name: CLOUDINARY_API_KEY
              ValueFrom: !Sub "${CloudinarySecretArn}:cloudinary_api_key::"
            - Name: CLOUDINARY_API_SECRET
              ValueFrom: !Sub "${CloudinarySecretArn}:cloudinary_api_secret::"
            - Name: FAPSHI_API_USER
              ValueFrom: !Sub "${FapshiSecretArn}:fapshi_api_user::"
            - Name: FAPSHI_API_KEY
              ValueFrom: !Sub "${FapshiSecretArn}:fapshi_api_key::"
            - Name: FAPSHI_BASE_URL
              ValueFrom: !Sub "${FapshiSecretArn}:fapshi_base_url::"
            - Name: JWT_SECRET
              ValueFrom: !Sub "${JWTSecretArn}:jwt_secret::"
            - Name: ADMIN_EMAIL
              ValueFrom: !Sub "${AdminSecretArn}:admin_email::"
            - Name: ADMIN_PASSWORD
              ValueFrom: !Sub "${AdminSecretArn}:admin_password::"
            - Name: ADMIN_JWT_SECRET
              ValueFrom: !Sub "${AdminSecretArn}:admin_jwt_secret::"

  # ------------------------------------------------------------
  # IAM ROLES
  # ------------------------------------------------------------
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvId}-${AppName}-EcsExecutionRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      Policies:
        - PolicyName: allowSecrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                Resource:
                  - !Ref MongoDBSecretArn
                  - !Ref CloudinarySecretArn
                  - !Ref FapshiSecretArn
                  - !Ref JWTSecretArn
                  - !Ref AdminSecretArn

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvId}-${AppName}-TaskRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"

  # ------------------------------------------------------------
  # TARGET GROUP & LISTENER RULE
  # ------------------------------------------------------------
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvId}-${AppName}-TargetGroup"
      Protocol: HTTP
      Port: !Ref ContainerPort
      TargetType: ip
      VpcId: !Ref VPC
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: "/"
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60

  ListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Sub "api.${DomainName}"
      ListenerArn: !Ref HttpsListener
      Priority: 1

  # ------------------------------------------------------------
  # ECS SERVICE
  # ------------------------------------------------------------
  EcsService:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: !Sub "${EnvId}-${AppName}"
      Cluster: !Ref ClusterArn
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: []
      LoadBalancers:
        - ContainerName: !Ref AppName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  # ------------------------------------------------------------
  # DNS RECORD
  # ------------------------------------------------------------
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "api.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !Ref LoadBalancerDNSName
        HostedZoneId: !Ref LoadBalancerCanonicalHostedZoneID

Outputs:
  ApiUrl:
    Description: API URL
    Value: !Sub "https://api.${DomainName}"
