AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a load balancer with a listener for HTTPS and HTTP redirect to HTTPS
Parameters:
  EnvId:
    Type: String
    Description: Environment Id (used to namespace resources)
    AllowedPattern: "[a-z][a-z0-9]{2,19}"
    ConstraintDescription: Must be lower case letters between 3 and 20 characters.

  VPC:
    Type: AWS::EC2::VPC::Id

  CertificateArn:
    Type: String

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids to deploy the load balancer into

# The following parameters are optional and are treated more as constants than inputs.
  LoadBalancerPort:
    Type: Number
    Default: 443

  DefaultHTTPPort:
    Type: Number
    Default: 80 

Resources:

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub "${EnvId}-EnvironmentLoadBalancerSecurityGroup"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref DefaultHTTPPort
          ToPort: !Ref DefaultHTTPPort
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Name: !Sub "${EnvId}-LoadBalancer"
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref SubnetIds

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
          - Type: "fixed-response"
            FixedResponseConfig:
              ContentType: "text/plain"
              MessageBody: "Unknown Host"
              StatusCode: "503"
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LoadBalancerPort
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref Certificate

      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LoadBalancerPort
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn



  ListenerHTTP:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: "redirect"
          RedirectConfig:
            Protocol: "HTTPS"
            Port: 443
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: "HTTP"


Outputs:
  HttpsListener:
    Description: The HTTPS listener for the load balancer
    Value: !Ref ListenerHTTPS
  LoadBalancerArn:
    Value: !Ref LoadBalancer
  LoadBalancerCanonicalHostedZoneID:
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName
  LoadBalancerSecurityGroupId:
    Value: !GetAtt LoadBalancerSecurityGroup.GroupId